### ISSUE TITLE
my question

### ISSUE THREAD

**Issue by feichenxue** [LincolnG4/GoMDF#2]
Hello, may I ask, is there any sample code for this package?

**Comment by LincolnG4** [comment]
Hello. Unfortunately the package is in beginning. So I don't have sample code running smoothly yet. I hope in some few weeks the read function will be finished.

**Comment by LincolnG4** [comment]
@feichenxue just out of curiosity, where do you intend to use the package more for reading or writing ?

**Comment by LincolnG4** [comment]
Already have some examples in examples and readme
