### ISSUE TITLE
The mf4.ReadFile method prints the comment by default, is it possible to add a token to control whether it needs to be printed or not?

### ISSUE THREAD

**Issue by Nmoumou** [LincolnG4/GoMDF#23]
![image](https://github.com/LincolnG4/GoMDF/assets/35753245/ced1f12d-1fc9-4c04-9691-b9282ebbcbf8)
Excuse me, as you can see above, in  command line usage, it is sometimes necessary to keep the output concise.
I see out output function in source mf4/mf4.go at line 75 etc, is it possible to add markers to control the output of these values?

**Comment by LincolnG4** [comment]
Sure. I will remove all those prints. It was made just to help me to debug and to study the mf4 files. In next the push they will not be there

**Comment by LincolnG4** [comment]
@Nmoumou I released a quick fix for this issue, I removed all unnecessary debug prints from the package and it should solve the issue from your side. 

`go get -u github.com/LincolnG4/GoMDF `

make sure you  are using version `v0.0.2`

Please update the package and let me know if you have any problem, otherwise please close the issue :) .

**Comment by Nmoumou** [comment]
@LincolnG4 Sorry for the late verification, I think the new version failed to compile for me because of the introduction of this library github.com/Pramod-Devireddy/go-exprtk, have you encountered this problem?
![image](https://github.com/LincolnG4/GoMDF/assets/35753245/90f20c18-2f71-4d86-a922-845c1dcf0ea3)

**Comment by LincolnG4** [comment]
Sorry the delay buddy

I could build the code normally.
![Screenshot from 2024-01-25 23-08-47](https://github.com/LincolnG4/GoMDF/assets/59087790/bd36a283-bb66-47a3-9a4b-d1b986570e58)

Could send me the sample code that you are using and the go.mod ?

**Comment by LincolnG4** [comment]
@Nmoumou sorry the delay

Yes I could build and run it normally
![Screenshot from 2024-01-25 23-08-47](https://github.com/LincolnG4/GoMDF/assets/59087790/c43c375b-cd80-45a4-9850-910ef56ff105)


Could you send me your code and go.mod ??

code that I built
```
package main

import (
	"fmt"
	"os"

	mf4 "github.com/LincolnG4/GoMDF/mf4"
)

func main() {
	file, err := os.Open("sample3.mf4")
	if err != nil {
		panic(err)
	}

	m, err := mf4.ReadFile(file)
	if err != nil {
		panic(err)
	}
	// Access metadata
	fmt.Println(m.Version())
	fmt.Println("Version ID --> ", m.MdfVersion())
	fmt.Println("Start Time NS --> ", m.GetStartTimeNs())
	fmt.Println("Start StartTimeLT --> ", m.GetStartTimeLT())

	// Get channel samples
	fmt.Println(m.ChannelNames())
	samples, err := m.GetChannelSample(0, "ActlEngPrcntTorqueHighResolution")
	if err != nil {
		panic(err)
	}
	fmt.Println(samples)
	// Download attachments
	// att := m.GetAttachments()[0]
	// m.SaveAttachment(att, "/PATH/TO/BE/SAVE/")

	// Read Change logs
	m.ReadChangeLog()
}

```

my go.mod

```
module mdf-reader

go 1.21

toolchain go1.21.4

require github.com/LincolnG4/GoMDF v0.0.2

require (
	github.com/Pramod-Devireddy/go-exprtk v1.1.0 // indirect
	github.com/davecgh/go-spew v1.1.1 // indirect
)
```

**Comment by Nmoumou** [comment]
Ok, let me check my environment, I'll close the problem first, thanks a lot!

**Comment by Nmoumou** [comment]
Ok, let me check my environment, I'll close the problem first, thanks a lot!

**Comment by LincolnG4** [comment]
@Nmoumou Keep me updated about your issue. Just let me know if I can help you with something

**Comment by LincolnG4** [comment]
Hi @Nmoumou 
I'm opening the issue again. As I mentioned, in my Linux PC the code built fine but today I tried to build in a Windows machine and I could replicate your issue. Looks like the go-exprt package has some issues to compile on Windows. I will work to migrate to a new package

**Comment by Nmoumou** [comment]
@LincolnG4 Yes, there is a problem with go-exprtk v1.1.0 on Windows, I've migrated the environment to linux, so it's fine

**Comment by LincolnG4** [comment]
@Nmoumou I migrated the package and now is compiling on windows
